# Bienvenue sur Jekyll
#
# Ce fichier de configuration est destiné aux paramètres qui affectent tout votre blog, les valeurs
# que vous êtes censé.e mettre en place une fois et rarement éditer après cela. Si vous vous retrouvez
# à éditer ce fichier très souvent, pensez à utiliser les fichiers de données de Jekyll
# pour les données que vous devez mettre à jour fréquemment.
#
# Pour des raisons techniques, ce fichier n'est *PAS* rechargé automatiquement lorsque vous utilisez
# 'bundle exec jekyll servir'. Si vous modifiez ce fichier, redémarrez le processus serveur.

# Paramètres du site
# Ils sont utilisés pour personnaliser votre nouveau site. Si vous regardez dans les fichiers HTML,
# vous verrez leur accès via {{site.title}}, {{site.email}}, et ainsi de suite.
# Vous pouvez créer n'importe quelle variable personnalisée que vous voulez, et elles seront accessibles
# dans les modèles via {{site.myvariable}}.

title: Christophe Ducamp
email: christophe@ducamp.me
description: > # ceci signifie d'ignorer les nouvelles lignes jusqu'à "baseurl:"
  Un premier pas pour étudier la configuration d'un site statique hébergé sur Github Pages. 
  Intention : apprendre à configurer un site personnel pour mes enfants et amis.
baseurl: "" # le sous-chemin de votre site, par exemple /blog
url: "http://christophe.ducamp.me" # le nom d'hébergeur et protocole de base de votre site, par exemple http://exemple.com
twitter_username: xtof_fr
github_username:  ChristopheDucamp

# Paramètres de construction
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
